# Generated by Django 3.2.5 on 2021-08-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_momouser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='momouser',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=64, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
