# Generated by Django 3.2.5 on 2021-08-03 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_momouser_useremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='momouser',
            name='useremail',
        ),
    ]
